### PR TITLE
Add new gcs 5.3 templates to the Traveller career templates

### PR DESCRIPTION
**Pull request by dripton**
There are some edge cases that don't work perfectly, like advantages and disadvantages with variable point values.  But it's a good start.

### CODE REVIEW

**Comment by richardwilkes** [comment]
I've only looked at the first one (Academician) so far and noticed that you have a "Pick 2" for Primary Skills where there are a bunch of 4 point skills... but also a container that has 8 points worth inside it. Thanks to the way things work, that container is treated as a single entry, so if you apply this template and select the container as one of your choices, you would still need to select a 4 point skill to go along with it. Is that what you actually intended?

**Comment by richardwilkes** [comment]
Note: I was thinking that maybe that "Secondary Skills" container was intended to be up a level and therefore not part of the "Pick 2" requirement.

**Comment by dripton** [comment]
Bug, secondary skills is supposed to be outside primary skills.  I went through the other templates and didn't see the same bug anywhere else, but it's always possible.  Will submit a fix.

**Comment by richardwilkes** [comment]
I also noticed in Bureaucrat that you have a "2 extra points in Primary or Secondary skills" and it appears that the intent is that they get added to existing skills. That, unfortunately, won't actually do what you're intending. You'll end up with the skill repeated. For example, if I chose Administration as one of the extras, I'd have Administration (4 points) and Administration (1 point) in my list when done.

**Comment by dripton** [comment]
Yeah, I don't see a better way to handle that within the current code.  If you pick different skills then it should work, but if you pick the same skill then some manual editing will be needed to clean things up later.  Do you see a way?

**Comment by richardwilkes** [comment]
No, I don't. It is worth creating an issue for the GCS repo to have some way to support that sort of thing. I do already intend to allow some sort of mechanism where points can be adjusted in the picker (i.e. where you say "pick 8 points worth" and you can then adjust any of the selection's actual point values to meet that criteria rather than relying on them being pre-set to specific values... of course, I'll want that to be a specific option to allow/disallow, since it isn't always appropriate.

**Comment by richardwilkes** [comment]
Anyway, I'm going to merge this. Thanks!

**Comment by dripton** [comment]
I will make an issue for this in the gcs repo.

**Pull request merged**
