### PR TITLE
Traveller Alien Races I-V & Aliens Templates

### PR DESCRIPTION
**Pull request by Tarrith**
Upload to the master Library request for alien racial templates

### CODE REVIEW

**Comment by dripton** [comment]
I imported your files into my GCS User Library and nothing blew up, so while there maybe be quibbles about exact values here or there, I think they're worth taking.

For the Traveller aliens see http://mygurps.com/pmwiki.php?n=Main.UpdatedTravellerRacialTemplates .  The author used to be the assistant GURPS line editor, so his 4E conversions should be about perfect, even though that's his personal page not an official SJG source.  So I would use his, for the aliens that he did.

For example, his Vargr is 16 points while yours is -12, mostly because he used Enhanced Move 1 with a 5% limitation for the early fatigue, while you used something much cheaper.

**Comment by Tarrith** [comment]
Ah nice, I'll have a look at that :)

**Review by richardwilkes — APPROVED** [review]
I only quickly glanced at these. If additional changes are needed, a follow-up PR can be submitted.

**Comment by Tarrith** [comment]
Cool thanks.
Yeah I'm sure there will be follow ups when people look at it and say...
"Oh no you messed that up, do it this way instead!"
;)

**Pull request merged**
