### PR TITLE
Added Lighten and fixed Fortify

### PR DESCRIPTION
**Pull request by Starfyre1**
Added Lighten 1 & 2 for Shields

Added Lighten 1 & 2 for Armor pieces

Fixed up cost and location for Fortify - left old version there for use with hit location items (didn't update values on old version.)

### CODE REVIEW

**Comment by ethorad** [comment]
Thanks, however you seem to be using the values from DF Magical Items 1 in the GCS DF1 library.  Since the values are different, it would be best to keep the DF1 library using the values from that book.

For example, DF1 page 30 shows Lighten 1 / 2 as costing $100 / $10,000 and Fortify 1 / 2 as costing $50 / $4,000.  However DF Magical Items 1 page 4 (which you have used) shows Lighten costs of $2,000 / $10,000 and Fortify as $1,000 / $4,000.

Are you able to amend this PR to reflect the values in DF1?

Thanks!

**Comment by Starfyre1** [comment]
Ok, Let me get ahold of GCS DF1

 

Dave Wagner

 

360.870.7064

**Comment by ethorad** [comment]
Don't feel you need to buy DF1 if you don't have it.  You could instead create a new library with all the stuff from DF Magical Items 1

**Comment by Starfyre1** [comment]
Ok… I’ll probably get around to it this weekend

 

Dave Wagner

 

360.870.7064

**Comment by Starfyre1** [comment]
I will close this and put the code in DFRPG Magic Items 1

**Pull request closed without merging**
