### PR TITLE
Fixed DFRPG Dwarf, Elf, Gnome, & Half-Ogre

### PR DESCRIPTION
**Pull request by jcklemme**
Made them correctly display attribute, reaction, conditional, and skill modifiers.  Also fixed an incorrect rule reference.

### CODE REVIEW

**Comment by jcklemme** [comment]
I may add a few more commits here, so I'll let you know when I'm done.

**Comment by richardwilkes** [comment]
I just prepped the master library for the upcoming GCS v5 release yesterday. I want all submissions going forward to be done using the new file formats, which means you'll need to either wait for me to do the actual release so that you can update things using the official release, or use the latest (unreleased) code to load and save these files and re-submit them.

**Comment by richardwilkes** [comment]
Oh, and since I failed to say so in the previous comment: thanks for building some racial templates!

**Comment by richardwilkes** [comment]
Hmm... my mistake. I didn't look closely enough and thought those were new. Still, thanks for the updates.

**Comment by jcklemme** [comment]
I will just wait until the release, these were very simple fixes so they will not be hard to redo at all.

**Comment by jcklemme** [comment]
Feel free to cancel or delete this pull request.

**Pull request closed without merging**
